# Generated by Django 6.0.1 on 2026-02-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_verified_user_otp_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("seller", "Sotuvchi"), ("buyer", "Haridor")],
                default="buyer",
                max_length=20,
            ),
        ),
    ]
